Repository enzodjabali/realm-of-the-righteous, pull requests merged in 2023-06, with the labels that each got.

#376 373 final balancing
  src/public/assets/images/amogus.png
  src/public/assets/images/badge.png
  src/public/assets/images/boardGame720.png
  src/public/assets/images/chemin.png
  src/public/assets/images/herbe.png
  src/public/assets/images/test.png
  src/public/assets/images/tour.png
  src/public/assets/images/zombie.gif
  src/public/js/Controller/HUDController.js
  src/public/js/Controller/TowerController.js
  src/public/js/Model/enumTower.js
  src/public/js/Vue/Display.js
Labels: enhancement, javascript

#380 implementing a leave game button and a start wave counter (#377)
  src/public/banishments.php
  src/public/game.php
  src/public/includes/hud.php
  src/public/js/Controller/Controller.js
Labels: enhancement

#379 378 fix on click path
  src/public/assets/css/board.css
  src/public/js/Controller/Controller.js
  src/public/js/Controller/FetchController.js
  src/public/js/Controller/HUDController.js
  src/public/js/Controller/TowerController.js
  src/public/js/Model/Tower.js
  src/public/js/Model/enumEnemies.js
  src/public/js/Model/enumTower.js
  src/public/js/Vue/Display.js
Labels: bug, javascript

#381 creating a new project tag (#378)
  README.md
Labels: documentation
